#系统级别的配置文件,在容器启动时读取
server:
  port: 80
spring:
  application:
    name: gateway
  redis:
    host: localhost
    port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
    gateway:  #基础的路由转发配置
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
#            allowCredentials: true
      routes: #查看配置源码
        - id: login  #唯一区别的名字
          uri: lb://s3-login #服务名
          order: 1
          predicates:
            - Path=/user/** #表示访问此网站所有路径都要  路由到uri为   百度的地址
        - id: static
          uri: lb://static
          order: 3
          predicates:
            - Path=/static/**
        - id: product
          uri: lb://product
          order: 4
          predicates:
            - Path=/product/**
management:
  endpoints:
    web:
      exposure:
        include: "*"    # 暴露gateway端点，* 是暴露全部端点
  endpoint:
    gateway:
      enabled: true # default value