spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fresh?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    password: 123456
    username: root
  application:
    name: s3-login
  redis:
    host: localhost
    port: 6379
  cloud:
    nacos:
      server-addr: localhost:8848 # 注册到哪
      # 配置nacos的信息
      discovery:
        username: nacos
        password: nacos


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启SQL语句打印
  mapper-locations: classpath:mapper/*.xml   #配置xml文件是 ，文件放置的地方

server:
  port: ${port:10020}
logging:
  level:
    root: info
    com.yc: info
    org.springframework: info
  file:
    path: ./logs
